### ISSUE TITLE
[Bug] I can not create file in open file directory

### ISSUE THREAD

**Issue by Kristinita** [noklesta/SublimeQuickFileCreator#15]
### Summary

I can not create file in open file directory.
### Expected behavior

Successful creating file in open file directory.
### Actual behavior

``` python
command: quick_create_file
Traceback (most recent call last):
  File "SublimeQuickFileCreator in E:\Sublime Text 3\Data\Installed Packages\Quick File Creator.sublime-package", line 83, in dir_selected
KeyError: 'E:\\Киролайна\\Jernl'
```
### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

For example, I open in Sublime Text tab for file `E:\Киролайна\Jernl\2016.jernl`. <kbd>Ctrl+Shift+P</kbd> → `Quick File Creator: Create File` → `E:\Киролайна\Jernl` → I get stack trace.

If I select in `Quick File Creator: Create File` panel any (including `Киролайна\Jernl`) folder of my sidebar, panel `File Name` open for me → I can create file.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Kristinita** [comment]
I migrate to Windows 64-bit EN LTSB, the problem not reproduce for me.

Thanks.

**Comment by Kristinita** [comment]
@noklesta, the problem sometimes reproduce for me.

```py
command: quick_create_file
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\Data\Packages\Quick File Creator\SublimeQuickFileCreator.py", line 83, in dir_selected
    self.selected_dir = self.full_torelative_paths[self.selected_dir]
KeyError: 'D:\\Sublime Text 3 x64\\Data\\Packages\\SashaSublime\\messages'
```

```py
command: quick_create_file
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\Data\Packages\Quick File Creator\SublimeQuickFileCreator.py", line 83, in dir_selected
    self.selected_dir = self.full_torelative_paths[self.selected_dir]
KeyError: 'D:\\Sublime Text 3 x64\\Data\\Packages\\User'
```

Thanks.
